# Generated by Django 4.1.7 on 2023-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(),
        ),
    ]
